apiVersion: v1
kind: Service
metadata:
  name: do-kubernetes-sample-app
  namespace: default
  labels:
    app: do-kubernetes-sample-app
spec:
  type: LoadBalancer
  selector:
    app: do-kubernetes-sample-app
  ports:
    - port: 80
      targetPort: http
      name: http
      nodePort: 31000
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
